version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install pip
          command: apk add --no-cache py-pip=9.0.0-r1
      - run:
          name: Install docker-compose
          command: pip install docker-compose==1.12.0
      - run:
          name: Test mmapi
          command: docker-compose -f circleci.yml run mmapi go test -v ./...
      - run:
          name: Test raceavg
          command: docker-compose -f circleci.yml run raceavg go test -v ./...